// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ColorTagController from "./color_tag_controller"
application.register("color-tag", ColorTagController)

import CoverPreviewController from "./cover_preview_controller"
application.register("cover-preview", CoverPreviewController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ProfileTabsController from "./profile_tabs_controller"
application.register("profile-tabs", ProfileTabsController)

import PostBannerController from "./post_banner_controller"
application.register("post-banner", PostBannerController)
